### ISSUE TITLE
Add a docker-compose.yml for the development dependencies

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#151]

**Comment by nickhammond** [comment]
Thoughts on moving to `ENV['DATABASE_URL']` in `.env`?  Rails will look there before config/database.yml.

**Comment by BookOfGreg** [comment]
@nickhammond It's actually easier to provide the `DATABASE_URL` in the docker-compose.yml under environment for the application. If you use the dotenv, you move to a non-standard and harder to configure setup that restricts you from certain classes of PaaS.

@colszowka Sorry I missed this issue until now. It's too easy to miss notifications on GitHub if you open them on the phone first, it makes them hard to find later!
database.yml can say localhost and will be overridden by the DATABASE_URL env due to precedence so no changed needed.

Docker-compose becomes something like: (Not run myself yet)
```yml
version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  postgres:
    image: postgres:9-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_USER: 'user'
  rubytoolbox:
    build: .
    image: rubytoolbox
    environment:
      DATABASE_URL: 'postgres://user:pass@postgres:5432/rubytoolbox_development'
      REDIS_URL: 'redis://redis:6379/0'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
```
