### ISSUE TITLE
Categorization

### ISSUE THREAD

**Issue by colszowka** [rubytoolbox/rubytoolbox#3]
Historically, categorization was manual, mostly by me and a handful contributors who used the "edit project" interface for sending in changes to the site. All this was backed by the postgres db. Similar categories were grouped in categories like "ActiveRecord Plugins" or "Background Processing"

Going forward, my preferred way to do this would be a github repo and changes via Pull Requests. We could go with a simple directory/yaml file structure like this:

```
Developer_Tools
-> Benchmarking.yml
-> Scripting_Frameworks.yml
```

Each .yml would look like:

```yaml
title: Scripting Frameworks
description:
  |
    Some long form description in markdown
projects:
  - rake
  - thor
  - ...
```

In #1 there were also suggestions to offload this to rubygem metadata itself. I do agree this would be nice, but at the very least we need a "backup" solution until all gem maintainers categorize all their projects, and regardless would probably need further discussion with the rubygems team.
